version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo-data:
    driver: local

# above code includes the following: but does not include the --net (network configuration).

# docker run -p27017:27017 -d \
# -e MONGO_INITDB_ROOT_PASSWORD=password \
# -e MONGO_INITDB_ROOT_USERNAME=root \
# --name mongodb \
# --net mongo-network \
# mongo

# docker run -d -p8081:8081  \
# -e ME_CONFIG_MONGODB_ADMINUSERNAME=root \
# -e ME_CONFIG_MONGODB_ADMINPASSWORD=password \
# --net mongo-network --name mongo-express \
# -e ME_CONFIG_MONGODB_SERVER=mongodb \
# mongo-express